use std::{
    collections::{BTreeMap, BTreeSet},
    fmt::Write as _,
    path::PathBuf,
};

use chrono::{DateTime, Local, Utc};

use crate::{
    analysis::{self, CompiledCleanupRule},
    models::{BoxMetadata, CommandEntry, Phase},
    rules::RuleBook,
};

#[derive(Debug, Clone)]
pub struct WriteupStats {
    pub raw_command_count: usize,
    pub visible_command_count: usize,
    pub hidden_command_count: usize,
    pub hidden_noise_count: usize,
    pub hidden_duplicate_count: usize,
    pub hidden_custom_count: usize,
    pub phase_counts: BTreeMap<Phase, usize>,
    pub ips: Vec<String>,
    pub ports: Vec<u16>,
    pub flags: Vec<String>,
    pub critical_commands: Vec<String>,
    pub first_seen: Option<DateTime<Utc>>,
    pub last_seen: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone)]
pub struct RenderedWriteup {
    pub markdown: String,
    pub stats: WriteupStats,
    pub path: PathBuf,
}

pub fn render_markdown(
    metadata: &BoxMetadata,
    entries: &[CommandEntry],
    phase_rules: &RuleBook,
    cleanup_rules: &[CompiledCleanupRule],
    path: PathBuf,
) -> RenderedWriteup {
    let cleanup = analysis::cleanup_entries_with_rules(entries, cleanup_rules);
    let visible_entries = cleanup.kept;
    let hidden_noise_count = cleanup
        .removed
        .iter()
        .filter(|removed| matches!(removed.reason, analysis::DropReason::ShellNoise))
        .count();
    let hidden_duplicate_count = cleanup
        .removed
        .iter()
        .filter(|removed| matches!(removed.reason, analysis::DropReason::ExactDuplicate))
        .count();
    let hidden_custom_count = cleanup
        .removed
        .iter()
        .filter(|removed| matches!(removed.reason, analysis::DropReason::Custom(_)))
        .count();

    let stats = collect_stats(
        &visible_entries,
        entries.len(),
        hidden_noise_count,
        hidden_duplicate_count,
        hidden_custom_count,
    );
    let mut markdown = String::new();

    let generated_at = Local::now().format("%Y-%m-%d %H:%M:%S %Z");
    let duration = format_duration(stats.first_seen, stats.last_seen);

    let _ = writeln!(markdown, "---");
    let _ = writeln!(markdown, "box: {}", metadata.name);
    let _ = writeln!(markdown, "platform: {}", metadata.platform.label());
    let _ = writeln!(markdown, "generated_at: {}", generated_at);
    let _ = writeln!(markdown, "---");
    let _ = writeln!(markdown);
    let _ = writeln!(markdown, "# {}", metadata.name);
    let _ = writeln!(markdown);
    let _ = writeln!(
        markdown,
        "> Auto-generated by PwnJournal. Edit this draft as needed."
    );
    let _ = writeln!(markdown);

    let _ = writeln!(markdown, "## Session Snapshot");
    let _ = writeln!(markdown, "| Field | Value |");
    let _ = writeln!(markdown, "| --- | --- |");
    let _ = writeln!(markdown, "| Platform | {} |", metadata.platform.label());
    let _ = writeln!(markdown, "| Box | {} |", escape_inline(&metadata.name));
    let _ = writeln!(
        markdown,
        "| Target IP | {} |",
        metadata
            .ip
            .as_deref()
            .map(escape_inline)
            .unwrap_or_else(|| "-".into())
    );
    let _ = writeln!(markdown, "| Raw commands | {} |", stats.raw_command_count);
    let _ = writeln!(
        markdown,
        "| Visible commands | {} |",
        stats.visible_command_count
    );
    let _ = writeln!(
        markdown,
        "| Filtered commands | {} |",
        stats.hidden_command_count
    );
    let _ = writeln!(markdown, "| Time span | {} |", duration);
    let _ = writeln!(
        markdown,
        "| Phase coverage | {} |",
        phase_coverage(&stats.phase_counts)
    );
    let _ = writeln!(markdown);

    if stats.hidden_command_count > 0 {
        let _ = writeln!(markdown, "## Cleanup Summary");
        let _ = writeln!(
            markdown,
            "PwnJournal automatically hid low-signal commands before generating the draft."
        );
        let _ = writeln!(
            markdown,
            "- Shell noise removed: {}",
            stats.hidden_noise_count
        );
        let _ = writeln!(
            markdown,
            "- Duplicate commands removed: {}",
            stats.hidden_duplicate_count
        );
        if stats.hidden_custom_count > 0 {
            let _ = writeln!(
                markdown,
                "- Custom cleanup rules triggered: {}",
                stats.hidden_custom_count
            );
        }
        let _ = writeln!(markdown);
    }

    if !stats.ips.is_empty() || !stats.ports.is_empty() || !stats.flags.is_empty() {
        let _ = writeln!(markdown, "## Observed Signals");
        if !stats.ips.is_empty() {
            let _ = writeln!(markdown, "- IPs: {}", join_inline_codes(&stats.ips));
        }
        if !stats.ports.is_empty() {
            let ports = stats
                .ports
                .iter()
                .map(|port| port.to_string())
                .collect::<Vec<_>>();
            let _ = writeln!(markdown, "- Ports: {}", join_inline_codes(&ports));
        }
        if !stats.flags.is_empty() {
            let _ = writeln!(markdown, "- Flags: {}", join_inline_codes(&stats.flags));
        }
        let _ = writeln!(markdown);
    }

    if !stats.critical_commands.is_empty() {
        let _ = writeln!(markdown, "## Critical One-Liners");
        let _ = writeln!(
            markdown,
            "These commands are worth keeping visible because they often carry the payload, pivot, or shell-spawn logic."
        );
        let _ = writeln!(markdown);
        for command in &stats.critical_commands {
            let _ = writeln!(markdown, "```bash");
            let _ = writeln!(markdown, "{}", command);
            let _ = writeln!(markdown, "```");
            let _ = writeln!(markdown);
        }
    }

    let grouped = group_by_phase(&visible_entries);
    for phase in Phase::ORDERED {
        let Some(items) = grouped.get(&phase) else {
            continue;
        };
        if items.is_empty() {
            continue;
        }

        let _ = writeln!(markdown, "## {}", phase.label());
        let _ = writeln!(markdown, "{}", phase.summary());
        let _ = writeln!(markdown);

        for (index, entry) in items.iter().enumerate() {
            let local_time = entry
                .timestamp
                .with_timezone(&Local)
                .format("%Y-%m-%d %H:%M:%S");
            let _ = writeln!(markdown, "### {}. {}", index + 1, local_time);
            let _ = writeln!(markdown, "- CWD: `{}`", escape_inline(&entry.cwd));
            let _ = writeln!(markdown, "- Phase: {}", entry.phase.label());
            if let Some(ip) = &entry.ip {
                let _ = writeln!(markdown, "- IP: `{}`", escape_inline(ip));
            }
            if !entry.ports.is_empty() {
                let ports = entry
                    .ports
                    .iter()
                    .map(|port| port.to_string())
                    .collect::<Vec<_>>();
                let _ = writeln!(markdown, "- Ports: {}", join_inline_codes(&ports));
            }
            if !entry.flags.is_empty() {
                let _ = writeln!(markdown, "- Flags: {}", join_inline_codes(&entry.flags));
            }
            if let Some(explanation) = &entry.explanation {
                let _ = writeln!(markdown, "- Heuristic: {}", explanation);
            }
            let analysis = analysis::analyze(&entry.command, phase_rules, Some(entry.phase));
            if !analysis.highlights.is_empty() {
                let _ = writeln!(
                    markdown,
                    "- Highlights: {}",
                    analysis.highlights.join(" | ")
                );
            }
            let _ = writeln!(markdown, "");
            let _ = writeln!(markdown, "```bash");
            let _ = writeln!(markdown, "{}", entry.command);
            let _ = writeln!(markdown, "```");
            let _ = writeln!(markdown);
        }
    }

    if stats.visible_command_count == 0 {
        let _ = writeln!(markdown, "## Draft Notes");
        if stats.raw_command_count == 0 {
            let _ = writeln!(
                markdown,
                "No commands were logged yet. Start the box and capture activity to populate this write-up."
            );
        } else {
            let _ = writeln!(
                markdown,
                "All logged commands were filtered out as noise or duplicates. Consider pruning the session or relaxing the cleanup rules."
            );
        }
        let _ = writeln!(markdown);
    }

    RenderedWriteup {
        markdown,
        stats,
        path,
    }
}

fn collect_stats(
    entries: &[CommandEntry],
    raw_count: usize,
    hidden_noise_count: usize,
    hidden_duplicate_count: usize,
    hidden_custom_count: usize,
) -> WriteupStats {
    let mut phase_counts = BTreeMap::new();
    for phase in Phase::ORDERED {
        phase_counts.insert(phase, 0);
    }

    let mut ips = BTreeSet::new();
    let mut ports = BTreeSet::new();
    let mut flags = BTreeSet::new();
    let mut critical_commands = Vec::new();
    let mut first_seen = None;
    let mut last_seen = None;

    for entry in entries {
        *phase_counts.entry(entry.phase).or_default() += 1;
        if let Some(ip) = &entry.ip {
            ips.insert(ip.clone());
        }
        for port in &entry.ports {
            ports.insert(*port);
        }
        for flag in &entry.flags {
            flags.insert(flag.clone());
        }
        if analysis::is_critical(&entry.command) {
            critical_commands.push(entry.command.clone());
        }

        first_seen = Some(
            first_seen.map_or(entry.timestamp, |current: DateTime<Utc>| {
                current.min(entry.timestamp)
            }),
        );
        last_seen = Some(last_seen.map_or(entry.timestamp, |current: DateTime<Utc>| {
            current.max(entry.timestamp)
        }));
    }

    WriteupStats {
        raw_command_count: raw_count,
        visible_command_count: entries.len(),
        hidden_command_count: raw_count.saturating_sub(entries.len()),
        hidden_noise_count,
        hidden_duplicate_count,
        hidden_custom_count,
        phase_counts,
        ips: ips.into_iter().collect(),
        ports: ports.into_iter().collect(),
        flags: flags.into_iter().collect(),
        critical_commands,
        first_seen,
        last_seen,
    }
}

fn group_by_phase(entries: &[CommandEntry]) -> BTreeMap<Phase, Vec<&CommandEntry>> {
    let mut grouped: BTreeMap<Phase, Vec<&CommandEntry>> = BTreeMap::new();
    for phase in Phase::ORDERED {
        grouped.insert(phase, Vec::new());
    }

    for entry in entries {
        grouped.entry(entry.phase).or_default().push(entry);
    }

    grouped
}

fn phase_coverage(phase_counts: &BTreeMap<Phase, usize>) -> String {
    Phase::ORDERED
        .iter()
        .map(|phase| {
            format!(
                "{}:{}",
                phase.short_label(),
                phase_counts.get(phase).copied().unwrap_or(0)
            )
        })
        .collect::<Vec<_>>()
        .join("  ")
}

fn escape_inline(value: &str) -> String {
    value.replace('`', "'")
}

fn join_inline_codes(values: &[String]) -> String {
    values
        .iter()
        .map(|value| format!("`{}`", escape_inline(value)))
        .collect::<Vec<_>>()
        .join(", ")
}

fn format_duration(first_seen: Option<DateTime<Utc>>, last_seen: Option<DateTime<Utc>>) -> String {
    let Some(first_seen) = first_seen else {
        return "-".to_string();
    };
    let last_seen = last_seen.unwrap_or(first_seen);
    let duration = last_seen - first_seen;
    let total_seconds = duration.num_seconds().max(0);
    let hours = total_seconds / 3600;
    let minutes = (total_seconds % 3600) / 60;
    let seconds = total_seconds % 60;
    format!("{}h {}m {}s", hours, minutes, seconds)
}

#[cfg(test)]
mod tests {
    use chrono::{TimeZone, Utc};

    use super::*;
    use crate::models::{BoxMetadata, EntrySource, Phase, Platform};

    #[test]
    fn renders_phase_sections_and_critical_commands() {
        let metadata = BoxMetadata::new("Demo", Platform::Htb, Some("10.10.10.10".into()));
        let entries = vec![
            CommandEntry {
                timestamp: Utc.with_ymd_and_hms(2026, 4, 29, 10, 0, 0).unwrap(),
                cwd: "/home/kali".into(),
                command: "nmap -sC -sV -p 22,80 10.10.10.10".into(),
                box_name: "Demo".into(),
                platform: Platform::Htb,
                phase: Phase::Scanning,
                explanation: Some("scan".into()),
                ip: Some("10.10.10.10".into()),
                ports: vec![22, 80],
                flags: vec![],
                source: EntrySource::Manual,
            },
            CommandEntry {
                timestamp: Utc.with_ymd_and_hms(2026, 4, 29, 10, 5, 0).unwrap(),
                cwd: "/home/kali".into(),
                command: "python3 -c 'print(\"HTB{demo}\")'".into(),
                box_name: "Demo".into(),
                platform: Platform::Htb,
                phase: Phase::Loot,
                explanation: Some("loot".into()),
                ip: None,
                ports: vec![],
                flags: vec!["HTB{demo}".into()],
                source: EntrySource::Manual,
            },
        ];

        let rules = RuleBook::builtin();
        let rendered = render_markdown(
            &metadata,
            &entries,
            &rules,
            &[],
            PathBuf::from("/tmp/writeup.md"),
        );
        assert!(rendered.markdown.contains("## Scanning"));
        assert!(rendered.markdown.contains("## Loot"));
        assert!(rendered.markdown.contains("Critical One-Liners"));
        assert_eq!(rendered.stats.visible_command_count, 2);
    }
}
